# Interface Utilisateur
ui:
  build: ./ui

# Interface Applicative
api:
  build: ./api
  links:
    - db:db

# Interface Applicative
views:
  build: ./views
  links:
    - db:db

# Base de données
db:
  build: ./db

# Gestion
mgmt:
  image: kibana:5.0.1
  environment:
    - ELASTICSEARCH_URL=http://db:9200
  links:
    - db
