# Interface Utilisateur
ui:
  ports:
  # Lie le port 80 du container ui au le port 80 de la machine hôte
    - "80:8080"

# Interface Applicative
api:
  ports:
  # Lie le port 80 du container api au port 8081 de la machine hôte
    - "8081:8081"

# Interface de visualisation
views:
  ports:
  # Lie le port 80 du container views au le port 8081 de la machine hôte
    - "8082:8082"

# Base de données
db:
  ports:
  # Lie les ports 9200 et 9300 du container db aux ports 9200 et 9300 de la machine hôte
    - "9200:9200"
    - "9300:9300"
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  volumes:
  # Monte les volumes de données et de sauvegarde
    - /data:/usr/share/elasticsearch/data
    - /backups:/usr/share/elasticsearch/backups

# Gestion
mgmt:
  ports:
    - "5601:5601"
